services:
  ########## DATABASES AND DATABASE TOOLING ##########

  # A postgres database instance which contains both the components database alongside the testing
  # database. Databases and users are configured in ./compose/db/docker-entrypoint-initdb.d/.
  db:
    profiles:
      - dev
      - prod
      - tool
      - test
    image: &db-image postgres:16
    environment:
      POSTGRES_PASSWORD: postgres-pass
    healthcheck:
      test:
        - CMD
        - pg_isready
        - --dbname
        - postgresql://components-user:components-pass@db:5432/components?sslmode=disable
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 120s
      start_interval: 1s
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  # psql command line tool running in the persisted database. Has the project root mounted
  # read-write under /workspace which is also the working directory.
  psql:
    profiles:
      - tool
    image: *db-image
    entrypoint:
      - "psql"
      - "--dbname"
      - postgresql://postgres:postgres-pass@db:5432/components?sslmode=disable
    working_dir: /workspace
    volumes:
      - ./:/workspace
    depends_on:
      db:
        condition: service_healthy

  # Run the diesel CLI tool with the backend directory mounted as the working directory
  diesel:
    profiles:
      - tool
    build:
      target: diesel-cli
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres-pass@db/components
    working_dir: /workdir
    volumes:
      - ./:/workdir
    depends_on:
      db:
        condition: service_healthy

  ########## SUPPORT SERVICES ##########

  # Run database migrations
  db-migrate:
    extends: diesel
    profiles:
      - dev
      - prod
      - tool
    command: ["migration", "run"]

volumes:
  db-data:
