version: "3"

tasks:
  default:
    cmds:
      - task: init
  init:
    desc: install pre-commit hooks, pull docker images and rebuild containers
    cmds:
      - pre-commit install
      - pre-commit install-hooks
      - task: compose-pull
      - task: compose-build
  down:
    desc: "stop running containers"
    cmds:
      - docker compose --profile=* down --remove-orphans
  down-hard:
    desc: "stop running containers and delete local volumes"
    cmds:
      - docker compose --profile=* down --volumes --remove-orphans
  psql:
    desc: "open a database shell"
    cmds:
      - docker compose run --rm psql {{.CLI_ARGS}}
  diesel:
    desc: "run diesel CLI tool"
    cmds:
      - docker compose run --rm diesel {{.CLI_ARGS}}
  compose-pull:
    desc: "pull remote images"
    cmds:
      - docker compose --profile=* pull
  compose-build:
    desc: "build local images"
    cmds:
      - COMPOSE_PARALLEL_LIMIT=1 docker compose --profile=* build {{.CLI_ARGS}}
